version: "3.8"
services:
  firstservice:
    image: simpleuiapp:1.0
    ports:
      - 3000:4000
    deploy:
      replicas: 3
  secondservice:
    image: simpleuiapp:1.0
    ports:
      - 3001:4000
    deploy:
      replicas: 2